#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Clean time directories only

rm -rf *[1-9]*
rm -r postProcessing
rm -r log.simpleFoam
# ----------------------------------------------------------------- end-of-file
